# Generated by Django 4.2.3 on 2025-01-23 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 19, 24, 28, 932758, tzinfo=datetime.timezone.utc)),
        ),
    ]
